Resources:
  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-webacl.html
  EpicAWSManagedRulesWebACL:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Name: EpicAWSManagedRulesWebACL
      Scope: REGIONAL
      Description: Web ACL for Epic Read Only
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true 
        CloudWatchMetricsEnabled: true 
        MetricName: MetricForEpicAWSManagedRulesACL
      Rules:
        - Name: AWS-AWSManagedRulesAmazonIpReputationList
          Priority: 0
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true 
            CloudWatchMetricsEnabled: true 
            MetricName: MetricForAMRIPReputationList
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList           
        - Name: AWS-AWSManagedRulesAnonymousIpList
          Priority: 10
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true 
            CloudWatchMetricsEnabled: true 
            MetricName: MetricForAMRAnonymousIpList
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAnonymousIpList            
        - Name: AWS-AWSManagedRulesAdminProtectionRuleSet
          Priority: 20
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true 
            CloudWatchMetricsEnabled: true 
            MetricName: MetricForAMRAdminProtection
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAdminProtectionRuleSet            
        - Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 30
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true 
            CloudWatchMetricsEnabled: true 
            MetricName: MetricForAMRKnownBadInputs
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet            
        - Name: AWS-AWSManagedRulesLinuxRuleSet
          Priority: 40
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true 
            CloudWatchMetricsEnabled: true 
            MetricName: MetricForAMRLinuxRules
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet            
        - Name: AWS-AWSManagedRulesSQLiRuleSet
          Priority: 50
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true 
            CloudWatchMetricsEnabled: true 
            MetricName: MetricForAMRSQLRules
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet            
        - Name: AWS-AWSManagedRulesUnixRuleSet
          Priority: 60
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true 
            CloudWatchMetricsEnabled: true 
            MetricName: MetricForAMRUnixRules
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesUnixRuleSet            
        - Name: AWS-AWSManagedRulesWindowsRuleSet
          Priority: 70
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true 
            CloudWatchMetricsEnabled: true 
            MetricName: MetricForAMRWindowsRules   
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesWindowsRuleSet              
  EpicManagedCoreWebACL:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Name: EpicAWSManagedCoreWebACL
      Scope: REGIONAL
      Description: Web ACL for AWS Managed Rules Common Rules
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true 
        CloudWatchMetricsEnabled: true 
        MetricName: MetricForEpicAWSManagedCoreACL
      Rules:
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 0
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true 
            CloudWatchMetricsEnabled: true 
            MetricName: MetricForAMRCommonRules
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet            

  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-webaclassociation.html
  EpicAWSManagedRulesWebACLtoHSWALB:
    Type: AWS::WAFv2::WebACLAssociation
    Properties: 
      ResourceArn: !ImportValue EpicRO-HSWALB
      WebACLArn: !GetAtt EpicAWSManagedRulesWebACL.Arn

  EpicAWSManagedRulesWebACLtoICFGALB:
    Type: AWS::WAFv2::WebACLAssociation
    Properties: 
      ResourceArn: !ImportValue EpicRO-ICFGALB
      WebACLArn: !GetAtt EpicAWSManagedRulesWebACL.Arn 

  EpicManagedCoreWebACLtoHSWALB:
    Type: AWS::WAFv2::WebACLAssociation
    Properties: 
      ResourceArn: !ImportValue EpicRO-HSWALB
      WebACLArn: !GetAtt EpicManagedCoreWebACL.Arn

  EpicManagedCoreWebACLtoICFGALB:
    Type: AWS::WAFv2::WebACLAssociation
    Properties: 
      ResourceArn: !ImportValue EpicRO-ICFGALB
      WebACLArn: !GetAtt EpicManagedCoreWebACL.Arn